### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [Selim042/SM-Rope-Ladders#1]
Is there a working discord link? This page has one but it's invalid. https://www.curseforge.com/minecraft/mc-mods/rope-ladders

**Comment by Selim042** [comment]
This project is dead.

**Comment by Fireworkstars46** [comment]
So there's none?

**Comment by Fireworkstars46** [comment]
Would a 16.1 version be added or no?

**Comment by Selim042** [comment]
Once more, this project is dead.  There is no support, there is no development.

**Comment by Fireworkstars46** [comment]
Is it open source though?

**Comment by Selim042** [comment]
Yes...look at the code tab.
